---
output: 
  word_document:
    toc: true
    toc_depth: 3
--- 

# Padrino digitization guide
The table of contents corresponds to each table in the database. Each column name in the sheet is below along with a brief description of the information it holds.  In addition to each this, links are provided to additional resources that explain more complicated columns in greater detail. 

## Metadata
ipm_id: 


species_author: 

 

species_accepted: 

 

tax_genus: 

 

tax_family: 

 

tax_order: 

 

tax_class: 

 

tax_phylum: 

 

kingdom: 

 

organism_type: 

 

dicot_monocot: 

 

angio_gymno: 

 

authors: 

 

journal: 

 

pub_year: 

 

doi: 

 

corresponding_author: 

 

email_year: 

 

remark: 

 

apa_citation: 

 

demog_appendix_link: 

 

duration: 

 

start_year: 

 

start_month: 

 

end_year: 

 

end_month: 

 

periodicity: 

 

population_name: 

 

number_populations: 

 

lat: 

 

lon: 

 

altitude: 

 

country: 

 

continent: 

 

ecoregion: 

 

studied_sex: 

 

eviction_used: 

 

evict_type: 

 

treatment: 

## StateVariables

ipm_id: 

 

state_variable: 

 

discrete: 

## DiscreteStates

ipm_id: 

 

state_variable: 

 

vr_expr_name: 

 

state_value: 

## DiscreteTransitions

ipm_id: 

 

state_variable: 

 

from: 

 

to: 

 

value: 

## ContinuousDomains

ipm_id: 

 

state_variable: 

 

domain: 

 

lower: 

 

upper: 

 

kernel_id: 

 
## QuadratureRoutines

ipm_id: 

 

state_variable: 

 

domain: 

 

n_meshpoints: 

 

integration_rule: 

 

kernel_id: 

 
## StateVectors

ipm_id: 

 

expression: 

 

kernel_id: 

 
## IpmKernels

ipm_id: 

 

kernel_id: 

 

formula: 

 

model_family: 

VitalRateExpr

ipm_id: 

 

demographic_parameter: 

 

formula: 

 

model_type: 

 

kernel_id: 

 

## ParameterValues
 

ipm_id: 

 

demographic_parameter: 

 

state_variable: 

 

parameter_name: 

 

parameter_value: 

 

## EnvironmentVariables
 

env_variable: 

 

vr_expr_name: 

 

env_range: 

 

env_function: 

 

kernel_id: 

 

