---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Padrino

Padrino a package for interacting with the demography data base of the same name. It will likely consist of wrappers to an SQL data base that itself houses a suite of all known, published integral projection models. It is the brain child of Roberto Salguero-Gomez and others. Currently, it does not exist (::_sad trombone_::), but we hope to change in that in the coming months.

##### Note: The repo is set to private and will be for the forseeable future. Keep this in mind when sharing code in this repo with others!!!

For now, all commits will go to the `master` branch as this is still so early in development that keeping a separate `devel` branch is pointless. This will change in the future.

If you think of others who could/should contribute, please let me know and I'll add them!


