---
output: word_document
---

**Figure 1**: An overview of general workflows with *Rpadrino*. The upper row of boxes displays the workflow, while the lower row provides additional details on each step and how _ipmr_ fits in to them. The first step is to download and subset PADRINO based on the research question at hand. At this point, if the research question calls for it, users may augment the PADRINO object with data from other sources. The extensive metadata table in PADRINO is designed to make this as straightforward as possible. Once the dataset is prepared, users can also generate automated reports on their data subset (1). After preparing the dataset, users create `proto_ipm` objects using a single function: `pdb_make_proto_ipm()`. This function translates PADRINO's syntax into *ipmr* code and then uses *ipmr* to generate the `proto_ipm` objects. All of these steps take place internally, and so users do not need to understand PADRINO's syntax or how *ipmr* works to move forward (2). Once `proto_ipm`s are created, users generate IPM objects with a single function, `pdb_make_ipm()`. Examples of how to modify default building settings are in each case study in the supplementary materials and in the function's documentation (3). Finally, *Rpadrino* provides some basic analytical machinery, including deterministic and stochastic growth rates and eigenvectors, the ability to make iteration kernels from sub-kernels, and mean kernels (4). Examples of how to conduct more complex analyses are included in the package vignettes and the case studies in the supplementary materials.